/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-04-08 17:16:44 UTC)
 * on 2016-04-14 at 19:15:47 UTC 
 * Modify at your own risk.
 */

package com.appspot.yabiapp.yabi.model;

import java.io.Serializable;

/**
 * Model definition for CloudEndpointsUserMerchantDetails.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the yabi. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CloudEndpointsUserMerchantDetails extends com.google.api.client.json.GenericJson implements Serializable {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private CloudEndpointsUserMerchant merchant;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<CloudEndpointsUserOffer> offers;

  /**
   * @return value or {@code null} for none
   */
  public CloudEndpointsUserMerchant getMerchant() {
    return merchant;
  }

  /**
   * @param merchant merchant or {@code null} for none
   */
  public CloudEndpointsUserMerchantDetails setMerchant(CloudEndpointsUserMerchant merchant) {
    this.merchant = merchant;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<CloudEndpointsUserOffer> getOffers() {
    return offers;
  }

  /**
   * @param offers offers or {@code null} for none
   */
  public CloudEndpointsUserMerchantDetails setOffers(java.util.List<CloudEndpointsUserOffer> offers) {
    this.offers = offers;
    return this;
  }

  @Override
  public CloudEndpointsUserMerchantDetails set(String fieldName, Object value) {
    return (CloudEndpointsUserMerchantDetails) super.set(fieldName, value);
  }

  @Override
  public CloudEndpointsUserMerchantDetails clone() {
    return (CloudEndpointsUserMerchantDetails) super.clone();
  }

}
