/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-04-08 17:16:44 UTC)
 * on 2016-04-14 at 19:15:47 UTC 
 * Modify at your own risk.
 */

package com.appspot.yabiapp.yabi.model;

/**
 * Model definition for CloudEndpointsUserResponse.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the yabi. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CloudEndpointsUserResponse extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("action_taken")
  private java.lang.String actionTaken;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long coins;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("display_text")
  private java.lang.String displayText;

  /**
   * A User message
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private CloudEndpointsUserUser user;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getActionTaken() {
    return actionTaken;
  }

  /**
   * @param actionTaken actionTaken or {@code null} for none
   */
  public CloudEndpointsUserResponse setActionTaken(java.lang.String actionTaken) {
    this.actionTaken = actionTaken;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCoins() {
    return coins;
  }

  /**
   * @param coins coins or {@code null} for none
   */
  public CloudEndpointsUserResponse setCoins(java.lang.Long coins) {
    this.coins = coins;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDisplayText() {
    return displayText;
  }

  /**
   * @param displayText displayText or {@code null} for none
   */
  public CloudEndpointsUserResponse setDisplayText(java.lang.String displayText) {
    this.displayText = displayText;
    return this;
  }

  /**
   * A User message
   * @return value or {@code null} for none
   */
  public CloudEndpointsUserUser getUser() {
    return user;
  }

  /**
   * A User message
   * @param user user or {@code null} for none
   */
  public CloudEndpointsUserResponse setUser(CloudEndpointsUserUser user) {
    this.user = user;
    return this;
  }

  @Override
  public CloudEndpointsUserResponse set(String fieldName, Object value) {
    return (CloudEndpointsUserResponse) super.set(fieldName, value);
  }

  @Override
  public CloudEndpointsUserResponse clone() {
    return (CloudEndpointsUserResponse) super.clone();
  }

}
