/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-04-08 17:16:44 UTC)
 * on 2016-04-14 at 19:15:47 UTC 
 * Modify at your own risk.
 */

package com.appspot.yabiapp.yabi.model;

import java.io.Serializable;

/**
 * Model definition for CloudEndpointsUserMerchant.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the yabi. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CloudEndpointsUserMerchant extends com.google.api.client.json.GenericJson implements Serializable{

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("android_app")
  private java.lang.String androidApp;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long category;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cover;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("email_id")
  private java.lang.String emailId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("invite_code")
  private java.lang.String inviteCode;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("ios_app")
  private java.lang.String iosApp;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long isActive;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String logo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long membership;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("mobile_number") @com.google.api.client.json.JsonString
  private java.lang.Long mobileNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("no_of_offers") @com.google.api.client.json.JsonString
  private java.lang.Long noOfOffers;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String password;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String website;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAndroidApp() {
    return androidApp;
  }

  /**
   * @param androidApp androidApp or {@code null} for none
   */
  public CloudEndpointsUserMerchant setAndroidApp(java.lang.String androidApp) {
    this.androidApp = androidApp;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCategory() {
    return category;
  }

  /**
   * @param category category or {@code null} for none
   */
  public CloudEndpointsUserMerchant setCategory(java.lang.Long category) {
    this.category = category;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCover() {
    return cover;
  }

  /**
   * @param cover cover or {@code null} for none
   */
  public CloudEndpointsUserMerchant setCover(java.lang.String cover) {
    this.cover = cover;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public CloudEndpointsUserMerchant setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmailId() {
    return emailId;
  }

  /**
   * @param emailId emailId or {@code null} for none
   */
  public CloudEndpointsUserMerchant setEmailId(java.lang.String emailId) {
    this.emailId = emailId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public CloudEndpointsUserMerchant setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getInviteCode() {
    return inviteCode;
  }

  /**
   * @param inviteCode inviteCode or {@code null} for none
   */
  public CloudEndpointsUserMerchant setInviteCode(java.lang.String inviteCode) {
    this.inviteCode = inviteCode;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIosApp() {
    return iosApp;
  }

  /**
   * @param iosApp iosApp or {@code null} for none
   */
  public CloudEndpointsUserMerchant setIosApp(java.lang.String iosApp) {
    this.iosApp = iosApp;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIsActive() {
    return isActive;
  }

  /**
   * @param isActive isActive or {@code null} for none
   */
  public CloudEndpointsUserMerchant setIsActive(java.lang.Long isActive) {
    this.isActive = isActive;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLogo() {
    return logo;
  }

  /**
   * @param logo logo or {@code null} for none
   */
  public CloudEndpointsUserMerchant setLogo(java.lang.String logo) {
    this.logo = logo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getMembership() {
    return membership;
  }

  /**
   * @param membership membership or {@code null} for none
   */
  public CloudEndpointsUserMerchant setMembership(java.lang.Long membership) {
    this.membership = membership;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getMobileNumber() {
    return mobileNumber;
  }

  /**
   * @param mobileNumber mobileNumber or {@code null} for none
   */
  public CloudEndpointsUserMerchant setMobileNumber(java.lang.Long mobileNumber) {
    this.mobileNumber = mobileNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public CloudEndpointsUserMerchant setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getNoOfOffers() {
    return noOfOffers;
  }

  /**
   * @param noOfOffers noOfOffers or {@code null} for none
   */
  public CloudEndpointsUserMerchant setNoOfOffers(java.lang.Long noOfOffers) {
    this.noOfOffers = noOfOffers;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPassword() {
    return password;
  }

  /**
   * @param password password or {@code null} for none
   */
  public CloudEndpointsUserMerchant setPassword(java.lang.String password) {
    this.password = password;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getWebsite() {
    return website;
  }

  /**
   * @param website website or {@code null} for none
   */
  public CloudEndpointsUserMerchant setWebsite(java.lang.String website) {
    this.website = website;
    return this;
  }

  @Override
  public CloudEndpointsUserMerchant set(String fieldName, Object value) {
    return (CloudEndpointsUserMerchant) super.set(fieldName, value);
  }

  @Override
  public CloudEndpointsUserMerchant clone() {
    return (CloudEndpointsUserMerchant) super.clone();
  }

}
